image: node:20

stages:
  - test
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/
  policy: pull-push

before_script:
  - npm ci --cache .npm --prefer-offline

test:
  stage: test
  script:
    - npm run test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"

deploy:
  stage: deploy
  script:
    - npm install -g @railway/cli
    - railway login --token $RAILWAY_TOKEN
    - railway up --service $RAILWAY_SERVICE_ID
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  needs: ["test"]